---
name: "Release"

on:
  release:
    types:
      - published

jobs:
  release:
    name: "Release opower"
    runs-on: ubuntu-latest
    steps:
      - name: "‚¨áÔ∏è Checkout the repository"
        uses: actions/checkout@v3

      - name: "üî¢ Adjust version number"
        shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          version="${version#v}"
          yq e -P -o=json \
            -i ".version = \"${version}\"" \
            "${{ github.workspace }}/custom_components/opower/manifest.json"
      - name: "üì¶ Created zipped release package"
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/opower"
          zip opower.zip -r ./
      - name: "‚¨ÜÔ∏è Upload zip to release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/opower/opower.zip
